config/routes.rb
Rbpm::Application.routes.draw do

  resources :systems do
    member do
      get :update_status
    end
  end

  resources :workers do
    collection do
      get :spawn
    end
  end

  resources :steps do
    member do
      get :follow
    end
  end
  
  resources :links  
  resources :jobs do
    member do
      get :reset
      get :push
    end
    collection do
      get :cleanup_successful
      get :reset_failed
    end
    collection do
      get :reset_failed
    end
  end
  
  resources :actions
  
  STEP_CLASSES.each do |class_name|
    resource_name = class_name.underscore.pluralize.to_sym
    resources resource_name, :controller => :steps
  end
  
  LINK_CLASSES.each do |class_name|
    resource_name = class_name.underscore.pluralize.to_sym
    resources resource_name, :controller => :links
  end

  get "webservice/getdate"
  get "webservice/wait"
  get "webservice/encode"
  get "webservice/checksum"

  get "graph/map/:id" => "graph#map", :as => :map_graph
  get "graph/job/:id" => "graph#job", :as => :job_graph
  get "graph/step/:id" => "graph#step", :as => :step_graph
  get "status/dashboard" => "status#dashboard", :as => :dashboard
  get "status/workflows" => "status#workflows", :as => :workflows
  get "status/editor" => "status#editor", :as => :workflow_editor
  get "monitor" => "status#monitor", :as => :monitor

  get "status/ajax_workers" => "status#ajax_workers", :as => :ajax_workers
  get "status/ajax_jobs" => "status#ajax_jobs", :as => :ajax_jobs
  get "status/ajax_system/:id" => "status#ajax_system", :as => :ajax_system

  root :to => 'status#workflows'

end

app/models/job.rb
# Remove transactions


class Job < ActiveRecord::Base
  #use_transactional_fixtures = false

  belongs_to :step
  has_many :actions, :dependent => :destroy
  has_many :vars, :dependent => :destroy
  
  accepts_nested_attributes_for :vars
  after_initialize :init_context_and_vars
  serialize :context, JSON
  
  scope :locked, where('NOT worker=""')
  scope :not_locked, where('worker=""')

  scope :completed, where('completed_at IS NOT NULL')
  scope :not_completed, where(:completed_at => nil)

  scope :failed, where('errno <> 0')
  scope :not_failed, where('NOT errno')

  scope :running, locked.not_completed
  scope :runnable, not_locked.not_completed.order(:id)
  scope :successful, not_failed.not_locked.completed

  # scope :failsafe_find_in, lambda do |job_ids|
  #   where('id in ?', )
  # end
  
  scope :failsafe_find_in, lambda { |ids|
    where('id in (?)', ids).includes(:step)
    }

  @logger = nil
  @beanstalk_job = nil
  @prefix = ""
  @vars = {}

  # def initialize
  #   #raise "init"
  #   self.refresh_vars!
  # end
  
  def init_context_and_vars
    self.context ||= {}
    #self.refresh_vars!
  end
  
  # def status_image_path
  #   if (self.errno != 0)
  #     return '/images/clock_red.png'
  #   elsif self.completed_at.nil?
  #     return '/images/clock.png'
  #   else
  #     return '/images/accept.png'
  #   end
  # end

  def init_vars_from_context!
    return unless self.context.is_a? Hash
    
    # Refresh local vars to avoid a split-brain between rails's record presence and real db presence
    self.refresh_vars!

    # Set job vars from initial_vars
    self.context.each do |name, value|
      self.set_var(name, value)
    end
  end

  def started_since
    return nil if self.started_at.nil?
    return Time.now - self.started_at
  end

  def timed_out?
    return false if self.started_at.nil?
    return started_since >= JOB_RELEASE_DEFAULT  
  end
  
  
  def refresh_vars!
    # Force vars reload from the db, and refresh the array
    @vars = {}
    self.vars.reload.each do |var|
      @vars[var.name.to_s] = var.value
    end
  end

  def set_var(name, value, step = nil, action = nil)
    # Update var in db
    Var.uncached do
      var = self.vars.find_or_create_by_name(name.to_s, :step => step, :action => action, :value => value)
      var.update_attributes(:step => step, :action => action, :value => value)
    end
    
    # Update var in local cache
    @vars[name.to_s] = value unless name.nil?
  end
  
  def get_var(name)
    return @vars[name.to_s] unless name.nil?
  end

  def get_vars
    return @vars
  end
  # 
  # def get_vars_hash
  #   #run_id = run.id unless run.nil?
  #   vars = {}
  #   self.vars.each do |var|
  #     vars[var.name.to_s] = var.value
  #   end
  #   return vars
  # end
  
  def unlock!
    self.update_attributes(:completed_at => nil, :locked => false)
  end
    
  def bootstrap
    return "(s#{self.step.id}) #{self.step.label}" unless self.step.nil?
  end
  
  def evaluate(expression)
    # Dont' do any replacement if expression is not a string
    return expression unless expression.is_a? String

    # Make a local copy
    output = expression.clone

    # Replace constants
    ENV_CONSTANTS.each do |name, value|
      pattern = "!#{name.to_s}"
      #return value if (output == pattern)
      output.gsub!(pattern, value.to_s)
    end

    # Replace internal values
    random = SecureRandom.hex(16)
    output.gsub!("#jobid", self.id.to_s) unless self.id.nil?
    output.gsub!("#random", random)
    output.gsub!("#now", Time.now.strftime("%Y%m%d-%H%M%S"))

    # Replace job vars
    @vars ||= {}
    @vars.each do |name, value|
      pattern = "$#{name.to_s}"
      #puts "comparing expression(#{expression}) with pattern (#{pattern}), data(#{var.data}) value(#{var.value}) name(#{var.name}) id(#{var.id})" 
      #return var.value if (output == pattern)
      output.gsub!(pattern, value.to_s)
    end

    # Return the final string
    return output
  end

  # def evaluate_uncached(expression)
  #   # Dont' do any replacement if expression is not a string
  #   return expression unless expression.is_a? String
  # 
  #   # Make a local copy
  #   output = expression.clone
  # 
  #   # Replace constants
  #   ENV_CONSTANTS.each do |name, value|
  #     next if value.nil?
  #     pattern = "!#{name.to_s}"
  #     #return value if (output == pattern)
  #     output.gsub!(pattern, value.to_s)
  #   end
  # 
  #   # Replace internal values
  #   random = SecureRandom.hex(16)
  #   output.gsub!("#jobid", self.id.to_s) unless self.id.nil?
  #   output.gsub!("#random", random)
  #   output.gsub!("#now", Time.now.strftime("%Y%m%d-%H%M%S"))
  # 
  #   # Replace job vars
  #   self.get_vars_hash_uncached.each do |name, value|
  #     next if value.nil?
  #     pattern = "$#{name}"
  #     output.gsub!(pattern, value)
  #   end
  # 
  #   # Return the final string
  #   return output
  # end

  def use_logger(logger, prefix="")
    @logger = logger
    @prefix = "#{prefix}[j#{self.id}]\t"
  end

  def use_beanstalk_job(beanstalk_job)
    @beanstalk_job = beanstalk_job
  end

  def touch_beanstalk_job
    @beanstalk_job.touch unless @beanstalk_job.nil?
  end

  def start!
    log "#############################################################################"
    log "## STARTING JOB (j#{self.id}) FROM #{self.bootstrap}"
    log "#############################################################################"
    
    # Initialize initial context into vars, create as many job.var's as needed
    log "initializing context: #{self.context.to_json}"
    self.init_vars_from_context!
     
    # Start execution from job's first step
    log "running from (s#{self.step.id})"

    return self.run_from(self.step)
  end
  
  def reset!
    # Remove all children, the powerfull way
    Var.delete_all(:job_id => self.id)
    Action.delete_all(:job_id => self.id)
    #self.actions.destroy_all
    #self.vars.destroy_all
    self.init_vars_from_context!

    # Flag it as clean
    self.completed_at = nil
    self.started_at = nil
    self.errno = 0
    self.errmsg = ""
    self.worker = ""

    self.save!
  end

  protected

  def run_from(from_step)
    # Init
    raise "EXITING: run_from expects a starting step" if from_step.nil?
    
    # Pass logger, beanstalk job to step
    from_step.use_logger(@logger, @prefix)
    #from_step.use_logger(@logger, "#{@prefix} [s#{from_step.id}]")
    from_step.use_beanstalk_job(@beanstalk_job)

    #################################
    ### RUNNING LOCAL STEP'S STUFF
    #################################

    # Preparing action
    action = self.actions.create(:step => from_step)
    log "s#{from_step.id}: type (#{from_step.type}), action (a#{action.id}), label (#{from_step.label})"

    # Validate step parameters
    if validation_error = from_step.validate_params?
      action.update_attributes(:errno => -1, :errmsg => "exiting: error with step parameters (#{validation_error})")
      raise Exceptions::JobFailedParamError, "validate_params failed (#{validation_error})"
      return
    end

    # Ping job
    log "s#{from_step.id}: touch job"
    self.touch_beanstalk_job
    
    # Reload job's vars
    self.refresh_vars!
    
    # Run this step and close the action
    log "s#{from_step.id}: running step"
    begin
      errno, errmsg, locals = from_step.run(self, action)
      
    rescue Exceptions => exception
      log "s#{from_step.id}: EXCEPTION [#{errno}: #{errmsg}] raising JobFailedStepRaised"
      
      # Store return codes into action
      action.update_attributes(:errno => errno, :errmsg => errmsg)
      
      # End this step execution
      raise Exceptions::JobFailedStepRaised, "#{errno}: #{errmsg}"
    end      
    
    # No exception was raised, let's see what the return code is
    if errno.zero?
      # Return code is ok
      errmsg_short = errmsg.gsub(/\n/," ").gsub(/\r/," ")[0...100]
      log "s#{from_step.id}: returned [#{errno}: #{errmsg_short}]"

      # Store return codes into action
      action.update_attributes(:errno => errno, :errmsg => errmsg, :completed_at => Time.now)
    else
      # As step returned an error, just stop here too
      log "s#{from_step.id}: ERRROR [#{errno}: #{errmsg}] raising JobFailedStepRun"

      # Store return codes into action
      action.update_attributes(:errno => errno, :errmsg => errmsg)

      # Then interrupt the process
      raise Exceptions::JobFailedStepRun, "[#{errno}: #{errmsg}]"
    end
    
    # FIXME: let's assume that a failed run stops the whole process


    #################################
    ### FOLLOWING LINKS
    #################################
    
    # Stacking and sorting all links
    blocking_threads = [] 
    nonblocking_threads = [] 
    typed_links = from_step.links.includes(:next).group_by(&:type)
    
    # Handling LinkBlocker links
    typed_links['LinkBlocker'].each do |link|
      next if link.next_id.nil?
      next_step = link.next
      blocking_threads << Thread.new() {
        log "s#{from_step.id}: #{link.type} > thread executing (s#{next_step.id}) #{next_step.label}"
        self.run_from(next_step)
        log "s#{from_step.id}: thread ending for (s#{next_step.id}) #{next_step.label}"
        }
      # remove this link from the stack
    end unless typed_links['LinkBlocker'].nil?
    # FIXME
    typed_links['LinkBlocker'] = []
    
    # Handling LinkFork links
    typed_links['LinkFork'].each do |link|
      next if link.next_id.nil?
      next_step = link.next
      log "s#{from_step.id}: #{link.type} > pushing job (s#{next_step.id}) #{next_step.label}"
      
      # Get a "locals" key of :label as the label 
      job_label = nil
      job_label = locals[:label].to_s if context.is_a? Hash
      
      # Creating a new, standalone job
      job = Job.create(:step => next_step, :creator => "workerd.fork(j#{self.id}, s#{from_step.id})", :label => job_label, :context => locals)

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    #@jobs = Job.order('id DESC').includes(:actions)
    @jobs = Job.includes(:step).order('id DESC')

    # Fetch real beanstalk queued IDs
    bs = Q.new
    @bs_jobs_ids = bs.fetch_queued_jobs_ids

    # Parse db jobs with bs job status
    @bs_job_status = {}
    begin
      @jobs.all.each do |job|
        logger.info "job (#{job.id})"
        @bs_job_status[job.id] = bs.job_stats(job.bsid)
      end
    rescue Beanstalk::NotFoundError
    end

    # Close connection to bs
    bs.close

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    @all_actions = @job.actions.order('actions.id ASC')
    @vars = @job.vars.order(:name)
    @running_actions = @job.actions.order('actions.id ASC').where('completed_at IS NULL').order(:id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @job }
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def push
    @job = Job.new()
    @job.creator = "admin.push"
    @job.step_id = params[:id]

    respond_to do |format|
      if @job.save

        # begin
        #   @job.push_to_beanstalk("jobs#push")
        # rescue Beanstalk::NotConnected
        #    redirect_to workflows_path, :notice => 'Could not connect to beanstalk server'
        #    return
        # end

        # Push this job onto the queue, and update job's bsid
        bs = Q.new
        bsid = bs.push_job(@job, JOB_PRIORITY_PUSHED)
        bs.close
        @job.update_attributes(:bsid => bsid)

        #format.html { redirect_to jobs_path, :notice => 'Job was successfully created.' }
        format.html { redirect_to @job, :notice => 'Job was successfully created.' }
        format.json { render :json => @job, :status => :created, :location => @job }
      else
        format.html { render :action => "new" }
        format.json { render :json => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:Job])
        format.html { redirect_to @job, :notice => 'Job was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    
    # Remove from BS
    bs = Q.new
    bs.pop_job(@job)
    bs.close
    
    # Remove from database
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :ok }
    end
  end
  
  def reset
    # Reset data for this job
    @job = Job.find(params[:id])
    @job.reset!

    # Push this job onto the queue, and update job's bsid
    bs = Q.new
    bsid = bs.push_job(@job, 50)
    @job.update_attributes(:bsid => bsid)

    #redirect_to jobs_path, :notice => 'Job was successfully reset'
    redirect_to job_path(@job), :notice => 'Job was successfully reset'
  end
  
  def cleanup_successful
    job_ids = Job.successful.map(&:id)
    
    # Batch-delete their vars and actions
    Var.delete_all(:job_id => job_ids)
    Action.delete_all(:job_id => job_ids)
    
    redirect_to jobs_path, :notice => "Successful jobs have been cleaned up (total: #{job_ids.count} jobs)"
  end
  
  def reset_failed
    jobs = Job.failed
    jobs.each do |job|
      # Reset data for this job
      job.reset!

      # Push this job onto the queue, and update job's bsid
      bs = Q.new
      bsid = bs.push_job(job, 50)
      job.update_attributes(:bsid => bsid)
    end
    redirect_to jobs_path, :notice => "Failed jobs have been reset (total: #{jobs.count} jobs)"
  end
  
end

app/helpers/jobs_helper.rb
module JobsHelper

  def job_status_badge(job, queued_job_ids = nil)
    # we have an error code
    if (job.errno != 0)            
      return badge(:error, "failed (error #{job.errno})", job.errmsg)
    end
      
    # the job has already completed
    if !job.completed_at.nil?    
      return badge(:success, "completed")
    end

    # # not completed, but we can guess the job has timed out
    # if job.timed_out?
    #   return badge(:warning, "timed out")
    # end

    # not completed, but not started neither, and we do have a queued status
    if job.started_at.nil? && (queued_job_ids.is_a?Array) && (queued_job_ids.include? job.id)
      return badge(:inverse, "queued")
    end

    # not completed, but not started neither, and we have no queued job array
    if job.started_at.nil?
      return badge(nil, "stale (not queued)")
    end
        
    # completed_at is nil, job has not timed out, thus it's waiintg
    return badge(:info, "locked")
  end
  
  def badge(klass, text, title = "")
    return content_tag(:span, text, :class => "badge badge-#{klass.to_s}", :title => title)
  end
  
end

app/views/jobs/index.html.haml
-# @sidebar = 'execution'
- set_title "Jobs"
- add_button :refresh, jobs_path, 'refresh'
- add_button :link, dashboard_path, "dashboard"

- add_button :link, cleanup_successful_jobs_path, "cleanup successful jobs"
- add_button :link, reset_failed_jobs_path, "reset failed jobs"


%table{:width => '100%'}
  %thead
    %tr
      %th ID
      %th Label / bootstrap
      %th Created
      %th Started
      %th Completed
      %th BSID
      %th Queue
      %th Worker
      %th
      %th
  %tbody
    - @jobs.each do |job|
      %tr
        %td= "j#{job.id}"
        %td
          - label = job.label.blank? ? "job ##{job.id}" : job.label
          = link_to label, job
          %br
          %i= job.bootstrap
        %td
          = my_datetime job.created_at
          %br
          %i= seconds_ago(Time.now - job.created_at)
        %td
          - if job.started_at.nil?
            ="-"
          - else
            = my_datetime job.started_at
            %br
            %i= seconds_ago(job.started_since)
        %td
          - if job.completed_at.nil?
            ="-"
          - else
            = my_datetime job.completed_at
            %br
            %i= "took #{job.completed_at - job.created_at}s"
        %td= job.bsid
        %td
          - status = @bs_job_status[job.id]
          - if status.is_a? Hash
            %table.small
              %tr
                %td ttr
                %td= status['ttr']
              %tr
                %td age
                %td= status['age']    
              %tr
                %td left
                %td= status['time-left']    
              %tr
                %td state
                %td= status['state']    
              %tr
                %td prio
                %td= status['pri']    
            =# @bs_job_status.to_json
          
        %td= job.worker
        -#
          %td.small
            - job.actions.order('id DESC').each do |action|
              %b
                = my_datetime action.created_at
              = " (s#{action.step.id}) #{action.step.label}" unless action.step.nil?
              %br
        %td
          = link_to 'destroy', job, :confirm => 'Are you sure?', :method => :delete
          %br
          = link_to 'reset', reset_job_path(job), :confirm => 'Are you sure?'
        %td
          =# image_tag job.status_image_path
          = job_status_badge(job, @bs_jobs_ids)


%br
%h4 Notes
%p
  A job will be released after running more than #{JOB_RELEASE_DEFAULT} seconds without keepalives.
  %br
  It will be made available to other workers, and run again
%p
  %strong ttr =
  time to run the whole jobs before being made ready
%p
  %strong left =
  time left for the current worker to complete
%p
  %strong state =
  one of (reserved, buried, ready)
%p
  %strong prio =
  relative priority index (default is 100, less is more urgent) 
      

app/views/jobs/show.html.haml
- set_title "Job j#{@job.id}"
- map_class =  @job.completed_at.nil? ? 'autorefresh' : 'completed'
- status_label =  @job.completed_at.nil? ? 'waiting' : 'completed'
- add_button :back, jobs_path
- add_button :refresh, job_path(@job), 'refresh'
- add_button :reset, reset_job_path(@job), "reset job"

%h3= "Status map (#{status_label})"
= image_tag job_graph_path(@job), :class => map_class

=# 12 cols available here
.row
  .span5
    %h3 Job description
    %table
      %tr
        %td First step
        - if @job.step.nil?
          %td (unspecified)
        - else
          %td s#{@job.step.id}: #{@job.step.label}
      %tr
        %td Label
        %td= @job.label
      %tr
        %td Creator
        %td= @job.creator
      %tr
        %td Created
        %td= @job.created_at
      %tr
        %td Completed?
        %td= @job.completed_at
      %tr
        %td Worker?
        %td= @job.worker
      %tr
        %td Result?
        %td
          = @job.errno unless @job.errno.zero?
          %br
          = @job.errmsg unless @job.errmsg.blank?

    %h3 Active actions
    - if @running_actions.empty?
      No running action
      %br
    - else
      %table
        %tr
          %th action
          %th step
          %th created
          %th updated
          %th completed
        - @running_actions.each do |action|
          %tr
            %td= "a#{action.id}"
            %td= "s#{action.step.id} - #{action.step.label}" 
            %td= my_datetime action.created_at
            %td= my_datetime action.updated_at
            %td= my_datetime action.completed_at

  .span7
    %h3 Initial context
    %table
      - @job.context.each do |name, value|
        %tr
          %td= name
          %td= value

    %h3 Variables
    %table
      %tr
        %th attribute
        %th value
        %th updated
        %th step
        %th action
      - @vars.each do |var|
        %tr
          %td= var.name
          %td= var.value.to_json
          -# %td= var.pretty_value
          %td= my_datetime var.updated_at
          %td= "s#{var.step.id} - #{var.step.label}"  unless var.step.nil?
          %td= "a#{var.action.id}" unless var.action.nil?

%h3 Actions history
%table
  %tr
    %th action
    %th step
    %th created
    %th updated
    %th completed
    %th errno
    %th errmsg
  - @all_actions.each do |action|
    %tr
      %td= "a#{action.id}"
      %td.nowrap= "s#{action.step.id} - #{action.step.label}" 
      %td= my_datetime action.created_at
      %td= my_datetime action.updated_at
      %td= my_datetime action.completed_at
      %td= action.errno
      %td
        %small
          = action.errmsg
%br