config/routes.rb
Rbpm::Application.routes.draw do

  resources :systems do
    member do
      get :update_status
    end
  end

  resources :workers do
    collection do
      get :spawn
    end
  end

  resources :steps do
    member do
      get :follow
    end
  end
  
  resources :links  
  resources :jobs do
    member do
      get :reset
      get :push
    end
    collection do
      get :cleanup_successful
      get :reset_failed
    end
    collection do
      get :reset_failed
    end
  end
  
  resources :actions
  
  STEP_CLASSES.each do |class_name|
    resource_name = class_name.underscore.pluralize.to_sym
    resources resource_name, :controller => :steps
  end
  
  LINK_CLASSES.each do |class_name|
    resource_name = class_name.underscore.pluralize.to_sym
    resources resource_name, :controller => :links
  end

  get "webservice/getdate"
  get "webservice/wait"
  get "webservice/encode"
  get "webservice/checksum"

  get "graph/map/:id" => "graph#map", :as => :map_graph
  get "graph/job/:id" => "graph#job", :as => :job_graph
  get "graph/step/:id" => "graph#step", :as => :step_graph
  get "status/dashboard" => "status#dashboard", :as => :dashboard
  get "status/workflows" => "status#workflows", :as => :workflows
  get "status/editor" => "status#editor", :as => :workflow_editor
  get "monitor" => "status#monitor", :as => :monitor

  get "status/ajax_workers" => "status#ajax_workers", :as => :ajax_workers
  get "status/ajax_jobs" => "status#ajax_jobs", :as => :ajax_jobs
  get "status/ajax_system/:id" => "status#ajax_system", :as => :ajax_system

  root :to => 'status#workflows'

end

app/controllers/status_controller.rb
require "sys/cpu"
include Sys

class StatusController < ApplicationController
  
  def dashboard
    # Prepare system
    @systems = System.order(:label)

    # Prepare jobs, workers
    bs = Q.new
    self.prepare_jobs(bs)
    self.prepare_workers(bs)

    # Close connection to the queue and process layout
    bs.close
  end  
  
  def ajax_workers
    # Prepare workers
    bs = Q.new
    self.prepare_workers(bs)

    # Collect queued job IDs
    @queued_jobs_ids = bs.fetch_queued_jobs.map{ |j| j.ybody[:id] }

    # Close connection to the queue and process layout
    bs.close
    render :partial => 'workers'
  end  

  def ajax_jobs
    # Prepare jobs
    bs = Q.new
    self.prepare_jobs(bs)

    # Close connection to the queue and process layout
    bs.close
    render :partial => 'jobs'
  end  

  def ajax_system
    @system = System.find(params[:id])
    @system.update_status!
    render :partial => 'system', :locals => {:system => @system}
  end  
  
  def monitor
    Facter.loadfacts  
    cpu_type = Facter.processor0 rescue '' + Facter.sp_cpu_type rescue ''
    
    # Build data response
    @json = {
      :hostname => `hostname`.chomp,
      :timestamp => Time.now.to_f,
      :loadavg => CPU.load_avg.first,
      :ipaddress => Facter.ipaddress,
      :uptime => Facter.uptime,
      :os => "#{Facter.operatingsystem} #{Facter.operatingsystemrelease}",
      :cpu_type => cpu_type,
      :architecture => "#{Facter.architecture} #{Facter.virtual}",
      :cpu_count => Facter.processorcount
    }

    # Send reply
    respond_to do |format|
      format.html
      format.json {
        render :json => @json
        }
    end
  end  
  
  def workflows
    @root_steps = Step.roots.includes(:links => :next).order('steps.label ASC')

    # Prepare graph
    graph = ProcessGraph.new

    # Highlight the current step and recurse around it
    #@step = @root_steps.first

    #@graph.map_recurse_around(@step.id, 2)
    graph.map_whole_database

    @graph_nodes = graph.get_nodes.values
    @graph_edges = graph.get_edges.values

  end

  def editor
    @root_step = Step.roots.order('steps.id DESC').first
  end

  protected

  def prepare_jobs(bs)
    # Collect queued job IDs in beanstalk
    @bs_jobs_ids = bs.fetch_queued_jobs_ids

    # Read jobs locked
    @jobs_locked = Job.locked.includes(:step).order('id DESC')

    # Read jobs failed
    jobs_failed = Job.failed.includes(:step).order('id DESC')
    @jobs_failed_count = jobs_failed.count
    @jobs_failed_limited = jobs_failed.limit(DASHBOARD_JOBS_LIMIT)
    
    # Read jobs queued
    jobs_queued = Job.failsafe_find_in(@bs_jobs_ids)
    @jobs_queued_count = jobs_queued.count
    @jobs_queued_limited = jobs_queued.limit(DASHBOARD_JOBS_LIMIT)

    # Find oprhan jobs
    @db_jobs_ids = jobs_queued.map(&:id) 
    @missing_in_db = @bs_jobs_ids - @db_jobs_ids
  end
  
  def prepare_workers(bs)
    @workers_list = bs.list_workers
    @workers_stats = bs.stats
    
    # Resolve jobs locked by one of these workers
    @workers_jobs = Job.where(:worker => @workers_list).group_by{ |j| j.worker }
  end
  
end

app/helpers/status_helper.rb
require 'base64'
module StatusHelper
  
  def job_status_image(job, timestamp = false)
    # Force loading all steps and lings
    logger.info "prefetching"
    Step.includes(:nexts, :params, :links).all
    Link.includes(:step, :next).all
    logger.info "done!"
    
    
    # Prepare graph
    graph = GraphMap.new
    #graph.prepare(true)
    graph.prepare(timestamp)

    # Initialize with job information
    graph.tag_with_job_status(job)
    
    # Last action registered
    # last_action = job.actions.order('id DESC').first
    # return if last_action.nil?
    # last_step_id = last_action.step_id
    # return if last_step_id.nil?
    
    # # Add steps around each running step
    # running_actions_step_ids = job.actions.where(:completed_at => nil).collect(&:step_id)
    # running_actions_step_ids.each do |step_id|
    #   graph.map_recurse_around(step_id, 0)
    # end
    
    # Graph the whole process
    graph.map_recurse_forward(job.step_id)

    # Generate output
    image_data = graph.output_to_string(:png)
    
    # And then, link!
    return tag :img, :src => inline_image_src("image/png", image_data), :class => :job_status_image
  end
  
  # def step_context(step)
  #   # Prepare graph
  #   graph = GraphMap.new
  #   graph.prepare(true)
  # 
  #   # Initialize with job information
  #   graph.tag_with_job_status(job)
  # 
  #   # Recurse
  #   graph.map_recurse(job.step_id)
  # 
  #   # Generate output
  #   image_data = graph.output_to_string(:png)
  #   
  #   # And then, link!
  #   return  tag :img, :src => inline_image_src("image/png", image_data), :width => 450
  # end

  def inline_image_src(content_type, data)
    #base64_data = escape_javascript(Base64.encode64(data))
    base64_data = Base64.encode64(data)
    return "data:#{content_type};base64,#{base64_data}"
  end
  
end

app/views/status/_jobs.haml
- unless @missing_in_db.size.zero?
  .alert.info
    %strong Missing job data
    %p
      Some queued jobs disappeared from our database, they will silently fail when made available to a worker:
      %br
      #{@missing_in_db.join(', ')}
      
%h3 Locked jobs (#{@jobs_locked.size})
- if @jobs_locked.empty?
  %p= "No locked job" 
- else
  %table{:width => '100%'}
    %tr
      %th job
      %th started
      %th worker
      %th bootstrap
      %th label
    - @jobs_locked.each do |job|
      %tr
        %td= link_to "j#{job.id}", job
        %td= my_datetime job.started_at
        %td= job.worker
        %td= job.bootstrap
        %td= job.label
    =# image_tag job.status_image_path
    =# link_to title, job
    =# link_to job_status_image(job), job
  

%h3 Queued jobs (#{@jobs_queued_count}) #{"showing first #{DASHBOARD_JOBS_LIMIT}" if (DASHBOARD_JOBS_LIMIT < @jobs_queued_count)}
- if @jobs_queued_limited.empty?
  %p= "No queued job" 
- else
  %table{:width => '100%'}
    %tr
      %th job
      %th created
      %th worker
      %th bootstrap
      %th label
    - @jobs_queued_limited.each do |job|
      %tr
        %td= link_to "j#{job.id}", job
        %td= my_datetime job.created_at
        %td -
        %td= job.bootstrap
        %td= job.label


%h3 Failed/suspended jobs (#{@jobs_failed_count}) #{"showing first #{DASHBOARD_JOBS_LIMIT}" if (DASHBOARD_JOBS_LIMIT < @jobs_failed_count)}
- if @jobs_failed_limited.empty?
  %p= "No failed job"
- else
  - if (DASHBOARD_JOBS_LIMIT < @jobs_failed_count)
    = "Showing only #{DASHBOARD_JOBS_LIMIT} first jobs out of #{@jobs_failed_count} in database"

  %table{:width => '100%'}
    %tr
      %th job
      %th started
      %th worker
      %th bootstrap
      %th label
    - @jobs_failed_limited.each do |job|
      %tr
        %td= link_to "j#{job.id}", job
        %td= my_datetime job.started_at
        %td= job.worker
        %td= job.bootstrap
        %td= job.label
  

app/views/status/_system.html.haml
:ruby
  system ||= System.new(:label => "DUMMY")
  status = system.status
  percent = system.load_percent

%h5
  = "#{system.label}"
  %small= " - up #{status['uptime']}" unless status['uptime'].blank?

%small
  = status['cpu_type'].to_s

.row
  .span1
    = "#{status['cpu_count']} CPUs" unless status['cpu_count'].blank?
  .span1
    = "load #{status['loadavg'].round(2)}" unless status['loadavg'].blank?
  .span1
    = "#{status['ipaddress']}" unless status['ipaddress'].blank?

.progress
  .bar{:style => "width: #{percent}"}
    = percent
  

app/views/status/_workers.html.haml
- attrs = ['uptime', 'current-workers', 'current-waiting', 'current-connections',
  'current-jobs-ready', 'current-jobs-reserved', 'current-jobs-buried', 'current-jobs-urgent', 'total-jobs', 'job-timeouts',
  'binlog-current-index']

%h3 Active workers (#{@workers_list.size})
%table
  %tr
    %th worker
    %th jobs
  - @workers_list.each do |worker_name|
    -# @workers_jobs[worker_name] ||= []
    %tr
      %td= worker_name
      - if @workers_jobs[worker_name].is_a? Array
        %td= @workers_jobs[worker_name].map{ |job| link_to("j#{job.id}", job).html_safe }.join(', ').html_safe
      - else
        %td -
        


%h3 Queue status
- if @workers_stats.nil?
  = "error: no stats returned"
- else

  %table
    %tr
      %th indicator
      %th value
    - attrs.each do |a|
      %tr
        %td= a 
        %td= @workers_stats[a]

  %xmp=# JSON.pretty_generate(@workers_stats).html_safe

%xmp
=# @workers_jobs.inspect

-#
  %h3 Jobs in the queue
  = @bs_jobs_ids.map{|j| "j#{j}" }.join(', ')

  %h3 Jobs ready in db
  = @db_jobs_ids.map{|j| "j#{j}" }.join(', ')

app/views/status/dashboard.html.haml
- set_title "Dashboard"
- add_button :refresh, dashboard_path, 'refresh'
- add_button :link, jobs_path, "jobs"

#dashboard.row

  .span5
    .refreshable{'data-source' => ajax_jobs_path, 'data-period' => DASHBOARD_JOBS_RATE}
      = render :partial => 'jobs'
  
  .span3
    .refreshable{'data-source' => ajax_workers_path, 'data-period' => DASHBOARD_WORKERS_RATE}
      = render :partial => 'workers'

  .span4
    %h3 Systems status

    - @systems.each do |system|
      .refreshable{'data-source' => ajax_system_path(system), 'data-period' => DASHBOARD_SYSTEM_RATE}
        = render :partial => 'system', :locals => {:system => system}
        
        

app/views/status/monitor.html.haml
- set_title "Monitor status"

%pre= JSON.pretty_generate(@json)

app/views/status/workflow.html.haml
-# @sidebar = 'authoring'
%h1 Available workflows

%ul
  - @root_steps.each do |root_step|
    %hr
    - job = Job.new(:step => root_step)
    = image_tag map_graph_path(root_step)
    = form_for job do |f|
      = f.hidden_field :step_id
      = f.submit "Create job from #{root_step.label} (s#{root_step.id})"
    

app/views/status/workflows.html.haml
- set_title "Available workflows"
- add_button :add, new_step_path(:start => true), "start a new workflow"

  %br
  = link_to "push job", push_job_path(root_step), :target => "_blank"
  |
  = link_to "edit", edit_step_path(root_step)
:javascript

  var graph = new joint.dia.Graph;
  var paper = new joint.dia.Paper({
      el: $('#graph'),
      width: '100%',
      height: 600,
      gridSize: 5,
      model: graph
  });

  // Intercept events
  paper.on('blank:pointerdown', function(evt, x, y) {
    alert('pointerdown on a blank area in the paper.')
  })

  // Inject data
  var cells4 = cells_from_hash(#{@graph_nodes.to_json.html_safe}, #{@graph_edges.to_json.html_safe});
  graph.resetCells(cells4);

  // Layout
  graph_layout(graph);

  // $('button.layout').on('click', graph_layout(graph));
  function force_graph_layout(graph, selector) {
    graph_layout(graph);
    $('#graph').effect('highlight', {}, 100);
    }
  $('button.layout').on('click', force_graph_layout);


%h2 Nodes
%pre= JSON.pretty_generate(@graph_nodes)

%h2 Edges
%pre= JSON.pretty_generate(@graph_edges)

app/views/status/workflows_old.html.haml
- set_title "Available workflows"
- add_button :add, new_step_path(:start => true), "start a new workflow"


- content_for :javascript do
  - @root_steps.each do |root_step|
    = render partial: '/dagre', locals: {nodes: @graph_nodes, edges: @graph_edges, target: "workflow#{root_step.id}"}


- @root_steps.each do |root_step|
  %hr
  =# image_tag map_graph_path(root_step)

  / $("svg#graph #node3").attr("class", "active");



  %br
  = link_to "push job", push_job_path(root_step), :target => "_blank"
  |
  = link_to "edit", edit_step_path(root_step)
  |
  = link_to "show", step_path(root_step)