config/routes.rb
Rbpm::Application.routes.draw do

  resources :systems do
    member do
      get :update_status
    end
  end

  resources :workers do
    collection do
      get :spawn
    end
  end

  resources :steps do
    member do
      get :follow
    end
  end
  
  resources :links  
  resources :jobs do
    member do
      get :reset
      get :push
    end
    collection do
      get :cleanup_successful
      get :reset_failed
    end
    collection do
      get :reset_failed
    end
  end
  
  resources :actions
  
  STEP_CLASSES.each do |class_name|
    resource_name = class_name.underscore.pluralize.to_sym
    resources resource_name, :controller => :steps
  end
  
  LINK_CLASSES.each do |class_name|
    resource_name = class_name.underscore.pluralize.to_sym
    resources resource_name, :controller => :links
  end

  get "webservice/getdate"
  get "webservice/wait"
  get "webservice/encode"
  get "webservice/checksum"

  get "graph/map/:id" => "graph#map", :as => :map_graph
  get "graph/job/:id" => "graph#job", :as => :job_graph
  get "graph/step/:id" => "graph#step", :as => :step_graph
  get "status/dashboard" => "status#dashboard", :as => :dashboard
  get "status/workflows" => "status#workflows", :as => :workflows
  get "status/editor" => "status#editor", :as => :workflow_editor
  get "monitor" => "status#monitor", :as => :monitor

  get "status/ajax_workers" => "status#ajax_workers", :as => :ajax_workers
  get "status/ajax_jobs" => "status#ajax_jobs", :as => :ajax_jobs
  get "status/ajax_system/:id" => "status#ajax_system", :as => :ajax_system

  root :to => 'status#workflows'

end

app/models/system.rb
class System < ActiveRecord::Base
  
  #scope recently_updated_first, order('updated_at - NOW')
  
  def update_status!
    puts "querying #{self.monitor_url}"
    return if self.monitor_url.blank?
    
    # Return cached data is updated less dans XXX seconds ago
    data_age = Time.now - self.updated_at
    
    if data_age < MONITOR_MIN_UPDATE_PERIOD.to_i
      status = self.status
      status[:cached] = true
      return status 
    end
    #@system.update_status!
    

    # Query for data
    resource = RestClient::Resource.new self.monitor_url
    
    begin
      response = resource.get
    rescue RestClient::ResourceNotFound => exception
      return {:failed => true}
    end
    puts " - received (#{response.size}) bytes"
    
    # Parse JSON response
    self.update_attributes(:status_json => response)
    #self.status_json = response
    return self.status
  end
  
  def status
    # Parse JSON response
    return JSON::parse(self.status_json) rescue {}
  end
  
  def status_pretty
    return JSON.pretty_generate(self.status)
  end
  
  def query2
    return {
      "timestamp" => Time.now,
      "cpu_count" => "4",
      "loadavg" => 1.07275390625,
      "cpu_desc" => "Intel x86_64",
      :dummy => true
    }
  end

  def load_percent
    data = self.status
    
    cpu_count = data['cpu_count'].to_i
    return nil if cpu_count.zero?
    percent = 100*(data['loadavg'].to_f / cpu_count)
    return "#{percent.round}%"
  end
    
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  # GET /systems
  # GET /systems.json
  def index
    @systems = System.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @systems }
    end
  end

  # GET /systems/1
  # GET /systems/1.json
  def show
    @system = System.find(params[:id])
    
    respond_to do |format|
      
      # When building plain HTML, just use the cached status
      format.html {
        @status = @system.status
        }
      
      # When building an ajax response, update the status before sending any reply
      format.json {
        #status = @system.update_status!
        
        # Chekc if we really got a valid reply
        if @system.status.empty?
          render :json => @system.errors, :status => :unprocessable_entity and return 
        end
        
        if status = @system.update_status!
          render :json => {
            :percent => @system.load_percent,
            :details => lines.join("<br>"),
            :timestamp => status['timestamp']
            }
        end
        }
    end
  end

  # GET /systems/new
  # GET /systems/new.json
  def new
    @system = System.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @system }
    end
  end

  # GET /systems/1/edit
  def edit
    @system = System.find(params[:id])
  end

  # POST /systems
  # POST /systems.json
  def create
    @system = System.new(params[:system])

    respond_to do |format|
      if @system.save
        format.html { redirect_to @system, :notice => 'System was successfully created.' }
        format.json { render :json => @system, :status => :created, :location => @system }
      else
        format.html { render :action => "new" }
        format.json { render :json => @system.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /systems/1  # PUT /systems/1.json
  def update
    @system = System.find(params[:id])

    respond_to do |format|
      if @system.update_attributes(params[:system])
        format.html { redirect_to @system, :notice => 'System was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @system.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update_status
    @system = System.find(params[:id])
    
    if @system.update_status!
      @system.save!
      redirect_to @system, :notice => 'Status data was successfully updated'
    else
      redirect_to @system, :error => 'Status data was bot updated'
    end
  end

  # DELETE /systems/1
  # DELETE /systems/1.json
  def destroy
    @system = System.find(params[:id])
    @system.destroy

    respond_to do |format|
      format.html { redirect_to systems_url }
      format.json { head :ok }
    end
  end
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/systems/_form.html.haml
= form_for @system do |f|
  -if @system.errors.any?
    #error_explanation
      %h2= "#{pluralize(@system.errors.count, "error")} prohibited this system from being saved:"
      %ul
        - @system.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :label
    = f.text_field :label
  .field
    = f.label :monitor_url
    = f.text_field :monitor_url
  .actions
    = f.submit 'Save'

app/views/systems/edit.html.haml
- set_title "Edit system"
- add_button :back, systems_path

= render 'form'

app/views/systems/index.html.haml
- set_title "Systems"
- add_button :add, new_system_path, "new system"

%table
  %tr
    %th Label
    %th URL
    %th Last update
    %th
    %th

  - @systems.each do |system|
    %tr
      %td= link_to system.label, system
      %td= system.monitor_url
      -#%td%small= system.status_pretty unless system.status.empty?
      %td= my_datetime system.updated_at
      %td= link_to 'edit', edit_system_path(system)
      %td= link_to 'destroy', system, :confirm => 'Are you sure?', :method => :delete

app/views/systems/new.html.haml
- set_title "New system"
- add_button :back, systems_path

= render 'form'

app/views/systems/show.html.haml
- set_title "System #{@system.label}"

- add_button :back, systems_path
- add_button :link, update_status_system_path(@system), "update remote data"

.row
  .span4
    %h3 Attributes
    %p
      %b Label:
      = @system.label
    %p
      %b Monitor url:
      = @system.monitor_url

    = link_to 'Edit', edit_system_path(@system)
    \|
    = link_to 'Back', systems_path

  .span4
    %h3 Query result
    %pre= JSON.pretty_generate(@status)  

    %p
      %b CPU description
      = @status['cpu_desc']

    %p
      %b CPU count
      = @status['cpu_count']

    %p
      %b Load average
      = @status['loadavg']

    %p
      %b Load
      = @load

    %p
      - percent = @system.load_percent
      .progress
        .bar{:style => "width: #{percent}"}
          = percent