config/routes.rb
Rbpm::Application.routes.draw do

  resources :systems do
    member do
      get :update_status
    end
  end

  resources :workers do
    collection do
      get :spawn
    end
  end

  resources :steps do
    member do
      get :follow
    end
  end
  
  resources :links  
  resources :jobs do
    member do
      get :reset
      get :push
    end
    collection do
      get :cleanup_successful
      get :reset_failed
    end
    collection do
      get :reset_failed
    end
  end
  
  resources :actions
  
  STEP_CLASSES.each do |class_name|
    resource_name = class_name.underscore.pluralize.to_sym
    resources resource_name, :controller => :steps
  end
  
  LINK_CLASSES.each do |class_name|
    resource_name = class_name.underscore.pluralize.to_sym
    resources resource_name, :controller => :links
  end

  get "webservice/getdate"
  get "webservice/wait"
  get "webservice/encode"
  get "webservice/checksum"

  get "graph/map/:id" => "graph#map", :as => :map_graph
  get "graph/job/:id" => "graph#job", :as => :job_graph
  get "graph/step/:id" => "graph#step", :as => :step_graph
  get "status/dashboard" => "status#dashboard", :as => :dashboard
  get "status/workflows" => "status#workflows", :as => :workflows
  get "status/editor" => "status#editor", :as => :workflow_editor
  get "monitor" => "status#monitor", :as => :monitor

  get "status/ajax_workers" => "status#ajax_workers", :as => :ajax_workers
  get "status/ajax_jobs" => "status#ajax_jobs", :as => :ajax_jobs
  get "status/ajax_system/:id" => "status#ajax_system", :as => :ajax_system

  root :to => 'status#workflows'

end

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : "Rbpm"
    = csrf_meta_tags
    :css
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    = stylesheet_link_tag "application", :media => "all"
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/


  %body.fluid
  
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "RBPM", dashboard_path, :class => "brand" 
          .container.nav-collapse
            %ul.nav
              %li= link_to "workflows", workflows_path
              %li= link_to "steps", steps_path
              %li= link_to "links", links_path
              %li= link_to "systems", systems_path
              %li= link_to "-"
              %li= link_to "dashboard", dashboard_path
              %li= link_to "jobs", jobs_path
              -#li= link_to "workers", workers_path

    .container-fluid
      .content
        %h1
          = @title unless @title.blank?

        - if @buttons.is_a? Array
          - @buttons.each do |type, path, text, method|
            - text = type.to_s if text.blank?
            - if method == :delete
              = link_to text, path, :method => :delete, :confirm => "Are you sure?", :class => "button icon #{type.to_s}"
            - else
              = link_to text, path, :class => "button icon #{type.to_s}"
          %br
          %br

          - flash.each do |type, message|
            .alert.fade.in{ "data-alert" => "alert", :class => twitterized_type(type) }
              %a.close{:href => "#", 'data-dismiss' => 'alert'} ×
              %strong= type
              %p
                = message
          -# flash.clear
            
        - if @sidebar.nil?
          = yield
        - else
          .row
            .span10
              = yield
            .span2
              .well.sidebar-nav
                %ul.nav.nav-list
                  = render :partial => "layouts/#{@sidebar}" unless @sidebar.blank?
    
      %footer.footer
        &copy; Bruno Medici 2011-2012
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"